services:
  appshell-react-host:
    image: appshell/react-host:${APPSHELL_IMAGE_TAG}
    build:
      context: '.'
      target: ${BUILD_TARGET}
      args:
        SOURCE_DIR: packages/react-host
    env_file: './${ENV_TARGET}.env'
    deploy:
      mode: replicated
      replicas: ${CONTAINER_SCALE}
    ports:
      - ${APPSHELL_PORT}:${APPSHELL_PORT}
    volumes:
      - ./${ENV_TARGET}.env:/appshell/${ENV_TARGET}.env
