services:
  host:
    image: appshell/react-host:${BUILD_TARGET}
    build:
      context: '.'
      target: ${BUILD_TARGET}
      args:
        SOURCE_DIR: packages/host
    env_file: './${ENV_TARGET}.env'
    command: ${CONTAINER_COMMAND}
    deploy:
      mode: replicated
      replicas: ${CONTAINER_SCALE}
    ports:
      - ${APPSHELL_PORT}:${APPSHELL_PORT}
    volumes:
      - ./packages:/appshell/packages
      - ./appshell_registry:/appshell/appshell_registry
      - ./${ENV_TARGET}.env:/appshell/${ENV_TARGET}.env
